"""
Hybrid Simulator — combines real-world traffic replays with synthetic attack injection.

This simulator uses the ReplaySimulator for benign traffic (from real CIC-IDS2017 data)
and injects synthetic attack flows generated by TrafficSimulator to create realistic
scenarios with controllable attack ratios.

Features:
  - Real benign traffic from historical data
  - Synthetic attacks with various patterns (DDoS, PortScan, BruteForce, Infiltration)
  - Configurable attack ratio and traffic speed
  - Device-aware traffic generation
"""

from __future__ import annotations

import os
import sys
import logging
from pathlib import Path
from typing import Optional, Tuple

import numpy as np

# Import from sibling modules
sys.path.insert(0, os.path.dirname(__file__))
from replay_simulator import ReplaySimulator, WINDOW_SIZE, NUM_FEATURES
from traffic_simulator import TrafficSimulator
from temporal_simulator import TemporalAttackSimulator, TemporalAttackGenerator

log = logging.getLogger("hybrid_simulator")


class HybridSimulator:
    """
    Generate hybrid traffic: real benign + synthetic attacks.
    
    This simulator:
    1. Uses ReplaySimulator to replay real benign CIC-IDS2017 traffic
    2. Uses TrafficSimulator to generate synthetic attack flows
    3. Injects attacks into the benign stream based on attack_ratio
    4. Supports device-specific simulation (metadata tracking)
    
    Parameters
    ----------
    data_dir : str
        Path to client training data (for ReplaySimulator)
    scenario_dir : str or None
        Path to scenario data (overrides data_dir if provided)
    attack_ratio : float
        Target fraction of windows that contain attacks (0.0-1.0)
    device_id : str or None
        Device identifier for metadata tracking
    client_id : str or None
        Client identifier for metadata tracking
    loop : bool
        Whether to loop when data is exhausted
    shuffle : bool
        Whether to shuffle window order
    seed : int or None
        Random seed for reproducibility
    """
    
    def __init__(
        self,
        data_dir: str = "/app/data",
        scenario_dir: Optional[str] = None,
        attack_ratio: float = 0.2,
        device_id: Optional[str] = None,
        client_id: Optional[str] = None,
        loop: bool = True,
        shuffle: bool = False,
        seed: Optional[int] = None,
        use_temporal: bool = True,
    ):
        self.attack_ratio = max(0.0, min(1.0, attack_ratio))
        self.device_id = device_id
        self.client_id = client_id
        self.seed = seed
        self.rng = np.random.default_rng(seed)
        self.use_temporal = use_temporal
        self._windows_generated = 0
        
        # Initialize the replay simulator for benign traffic
        try:
            self.replay_sim = ReplaySimulator(
                data_dir=data_dir,
                scenario_dir=scenario_dir,
                loop=loop,
                shuffle=shuffle,
                seed=seed,
            )
            log.info(
                "HybridSimulator initialized: data_dir=%s, attack_ratio=%.2f, "
                "device=%s, client=%s, temporal=%s",
                data_dir, attack_ratio, device_id, client_id, use_temporal
            )
        except Exception as exc:
            log.error("Failed to initialize ReplaySimulator: %s", exc)
            raise
        
        # Initialize the traffic simulator for attack generation
        if use_temporal:
            # Use temporal attack generator for realistic escalating attacks
            self.traffic_sim = TemporalAttackGenerator(seed=seed)
            log.info("Using TemporalAttackGenerator for realistic attack patterns")
        else:
            # Use simple traffic simulator
            self.traffic_sim = TrafficSimulator(attack_ratio=1.0, seed=seed)
            log.info("Using simple TrafficSimulator for attacks")
        
        self._window_buffer = []
        self._label_buffer = []
        
    def generate_window(
        self, window_size: int = WINDOW_SIZE
    ) -> Tuple[np.ndarray, dict]:
        """
        Generate a window of traffic with optional attack injection.
        
        Returns
        -------
        (window, metadata)
            window: np.ndarray of shape (window_size, 78) - traffic features
            metadata: dict with timestamp, labels, device_id, client_id, etc.
        """
        is_attack_window = self.rng.random() < self.attack_ratio
        
        if is_attack_window:
            # Generate an attack window using temporal or simple simulator
            attack_window = np.zeros((window_size, NUM_FEATURES), dtype=np.float32)
            attack_labels = []
            attack_intensities = []
            
            for i in range(window_size):
                if self.use_temporal:
                    # TemporalAttackGenerator returns (flow, metadata_dict)
                    flow, flow_meta = self.traffic_sim.generate_flow()
                    attack_intensities.append(flow_meta.get("intensity", 0.5))
                else:
                    # TrafficSimulator returns (flow, label)
                    flow, label = self.traffic_sim.generate_flow()
                    attack_intensities.append(1.0 if label else 0.0)
                
                attack_window[i] = flow
                attack_labels.append(1)
            
            window = attack_window
            labels = attack_labels
            has_attack = True
            avg_intensity = np.mean(attack_intensities) if attack_intensities else 1.0
        else:
            # Get a benign window from replay
            window, true_label, attack_fraction = self.replay_sim.get_next_window()
            labels = [true_label]
            has_attack = bool(true_label)
            avg_intensity = 0.0
        
        self._windows_generated += 1
        
        metadata = {
            "window_id": self._windows_generated,
            "device_id": self.device_id,
            "client_id": self.client_id,
            "has_attack": has_attack,
            "attack_count": sum(labels) if labels else 0,
            "attack_ratio": sum(labels) / len(labels) if labels else 0.0,
            "window_size": window_size,
            "is_synthetic": is_attack_window,
            "intensity": avg_intensity,
            "temporal": self.use_temporal and is_attack_window,
        }
        
        return window, metadata
    
    def generate_batch(
        self, batch_size: int = 1, window_size: int = WINDOW_SIZE
    ) -> Tuple[np.ndarray, list[dict]]:
        """
        Generate a batch of traffic windows.
        
        Returns
        -------
        (batch, metadata_list)
            batch: np.ndarray of shape (batch_size, window_size, 78)
            metadata_list: list of dicts with metadata for each window
        """
        windows = []
        metadata_list = []
        
        for _ in range(batch_size):
            window, meta = self.generate_window(window_size)
            windows.append(window)
            metadata_list.append(meta)
        
        return np.array(windows, dtype=np.float32), metadata_list
    
    def reset(self) -> None:
        """Reset to the beginning of the dataset."""
        if hasattr(self.replay_sim, 'reset'):
            self.replay_sim.reset()
        self._windows_generated = 0
        log.info("HybridSimulator reset")


# Convenience functions for direct use
def create_hybrid_simulator(
    device_id: str,
    client_id: str,
    attack_ratio: float = 0.2,
    data_dir: str = "/app/data",
    scenario_dir: Optional[str] = None,
    seed: Optional[int] = None,
) -> HybridSimulator:
    """
    Factory function to create a HybridSimulator for a specific device.
    
    Parameters
    ----------
    device_id : str
        Device identifier
    client_id : str
        Client identifier
    attack_ratio : float
        Fraction of traffic that should be attacks
    data_dir : str
        Path to client data
    scenario_dir : str or None
        Path to scenario data
    seed : int or None
        Random seed
    
    Returns
    -------
    HybridSimulator
        Initialized simulator ready to generate traffic
    """
    return HybridSimulator(
        data_dir=data_dir,
        scenario_dir=scenario_dir,
        attack_ratio=attack_ratio,
        device_id=device_id,
        client_id=client_id,
        loop=True,
        shuffle=False,
        seed=seed,
        use_temporal=True,  # Enable realistic temporal attack patterns
    )
